# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06d42fff5c149ae9e49ac867bd5eecdf"
name = "7n-shop-admin"
application_url = "https://shopify-7nshop-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

    [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/cancelled", "checkouts/update" ]
  uri = "/webhooks/orders/create"
 
  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "/webhooks/customer"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,read_content,read_customer_events,read_customers,read_discounts,read_orders,read_pixels,read_price_rules,read_products,read_themes,write_content,write_customers,write_discounts,write_orders,write_pixels,write_price_rules,write_themes"

[auth]
redirect_urls = [
  "https://shopify-7nshop-app.onrender.com/auth/callback",
  "https://shopify-7nshop-app.onrender.com/auth/shopify/callback",
  "https://shopify-7nshop-app.onrender.com/api/auth"
]
 
[app_proxy]
url = "https://shopify-7nshop-app.onrender.comapp/custom-proxy"
subpath = "public"
prefix = "apps"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
