import { authenticate } from "../shopify.server";
import db from "../db.server";
import { updateCleverTapWallet, sendCleverTapEvent } from "../utlis/clevertap.server";

export const action = async ({ request }) => {
  const { admin, topic, shop, payload } = await authenticate.webhook(request);

  console.log(`\n WEBHOOK: ${topic} | SHOP: ${shop}\n`);


  const shopifyOrderId = payload.admin_graphql_api_id || `gid://shopify/Order/${payload.id}`;
  const readableOrderNumber = payload.name || String(payload.order_number);
  const customerIdString = payload.customer ? String(payload.customer.id).trim() : "";
  const customerEmail = payload.customer ? payload.customer.email : "";
  const ctIdentity = customerEmail ? customerEmail.trim() : String(customerIdString).trim();
  const settings = await db.userSetting.findFirst({ where: { shop: shop } });
  const ratio = settings?.earnPercentage || 10;
  
  if (topic === "ORDERS_CREATE" || topic === "orders/create") {

    const orderTotal = parseFloat(parseFloat(payload.total_price || "0"));
    const discountUsed = parseFloat(parseFloat(payload.total_discounts || "0"));
    const subtotalPrice = parseFloat(payload.total_line_items_price || "0");
    let pointsEarnedForHistory = 0;
    let highRewardPointForHistory = 0;
    let usedCouponCode = null;
    if (payload.discount_applications?.length > 0) {
      usedCouponCode = payload.discount_applications[0].title || payload.discount_applications[0].code;
    }
   
    const cleanCouponCode = usedCouponCode ? String(usedCouponCode).trim() : "";
    const isAutoGeneratedReward = cleanCouponCode.startsWith("REWARD-");
    try {
      const settings = await db.userSetting.findFirst({ where: { shop: shop } });

      let existingReward = await db.rewardPoint.findFirst({
        where: { customerId: customerIdString, store: shop },
      });

      if (!existingReward) {
        existingReward = await db.rewardPoint.create({
          data: { 
            customerId: customerIdString, store: shop, 
            pointValue: 0, activePoint: 0, pendingPoint: 0, 
            customerEmail: customerEmail 
          },
        });
      }
      
      const currentRewardPointId = existingReward.id;

      const previousOrderCount = await db.orderHistory.count({ 
        where: { rewardPointId: currentRewardPointId } 
      });
      const isFirstOrder = (previousOrderCount === 0);

      // ----------------------------------------------------
      // A. REDEEM LOGIC: Jab Discount Code Apply ho (Debit)
      // ----------------------------------------------------
      if (discountUsed > 0 && isAutoGeneratedReward) {
        console.log(` [REDEEM] Deducting ${discountUsed} points...`);

        await db.rewardPoint.update({
          where: { id: currentRewardPointId },
          data: { 
            pointValue: { decrement: Math.min(discountUsed, existingReward.pointValue) },
            activePoint: { decrement: Math.min(discountUsed, existingReward.activePoint) }
          },
        });

        // CleverTap Debit API
        await updateCleverTapWallet(ctIdentity, discountUsed, "DEBIT", readableOrderNumber, orderTotal, `Redeemed for #${readableOrderNumber}`, shop, "ACTIVE");
        await sendCleverTapEvent(ctIdentity, "Points Redeemed", { "Points": discountUsed, "Order_ID": readableOrderNumber }, shop);     
      }

      // ----------------------------------------------------
      // B. EARN LOGIC: Sirf First Order ke liye (Pending)
      // ----------------------------------------------------
    //  pointsEarnedForHistory = parseFloat(((orderTotal * ratio) / 100).toFixed(2));

    //   if (pointsEarnedForHistory > 0) {
    //     console.log(` [EARN] Adding ${pointsEarnedForHistory} points to PENDING for Order #${readableOrderNumber}`);
        
    //     // Har order ke points pehle Pending mein jayenge
    //     await db.rewardPoint.update({
    //       where: { id: currentRewardPointId },
    //       data: { pendingPoint: { increment: pointsEarnedForHistory } },
    //     });

    //     // Timer wala function call karein jo points ko Active karega
    //     processPendingToActive(
    //       ctIdentity, 
    //       pointsEarnedForHistory, 
    //       readableOrderNumber, 
    //       orderTotal, 
    //       shop, 
    //       currentRewardPointId
    //     );

    //     await sendCleverTapEvent(ctIdentity, "Reward Points Pending", {
    //       "Points": pointsEarnedForHistory, 
    //       "Order_ID": readableOrderNumber
    //     }, shop);
    //   }

      // ----------------------------------------------------
      // C. SAVE HISTORY & DELETE DISCOUNT
      // ----------------------------------------------------
      let allProductNames = payload.line_items ? payload.line_items.map(item => item.name).join(", ") : "";
      await db.orderHistory.create({
        data: {
          orderId: shopifyOrderId, orderNumber: readableOrderNumber, productNames: allProductNames,
          discountAmount: discountUsed, couponCode: isAutoGeneratedReward ? cleanCouponCode : null, 
          subtotal: subtotalPrice, pointsEarned: 0, 
          highRewardPoint: 0,
          pointsRedeemed: discountUsed, rewardPointId: currentRewardPointId, status: pointsEarnedForHistory > 0 ?"PROCESSED" : "PENDING",// Mark ACTIVE for Cron
        }
      });

      // ----------------------------------------------------
      // 3. DELETE DISCOUNT FROM SHOPIFY
      // ----------------------------------------------------
      if (discountUsed > 0 && admin && isAutoGeneratedReward) {
        try {
          const searchTitle = `REWARD-${customerIdString}`;
          console.log(` [SHOPIFY] Searching for Discount starting with: ${searchTitle}`);
          const response = await admin.graphql(
            `#graphql
            query FindDiscount($query: String!) {
              discountNodes(first: 10, query: $query) {
                edges {
                  node {
                    id
                    discount {
                      __typename
                      ... on DiscountCodeBasic { title }
                      ... on DiscountAutomaticBasic { title }
                    }
                  }
                }
              }
            }`,
            { variables: { query: `title:${searchTitle}*` } }
          );
          
          const data = await response.json();
          const targetDiscount = data.data?.discountNodes?.edges?.find(e => {
              const title = e.node.discount?.title;
              return title && title.startsWith(searchTitle);
          });
          if (targetDiscount) {
            const discountId = targetDiscount.node.id;
            const discountType = targetDiscount.node.discount.__typename;
            console.log(` [SHOPIFY] Found ${discountType}. Deleting ID: ${discountId}`);
            const deleteMutation = `#graphql
              mutation discountCodeDelete($id: ID!) {
                discountCodeDelete(id: $id) {
                  deletedCodeDiscountId
                  userErrors { field message }
                }
              }
            `;

            const deleteResponse = await admin.graphql(deleteMutation, { variables: { id: discountId } });
            const deleteData = await deleteResponse.json();
            const deletedId = deleteData.data?.discountCodeDelete?.deletedCodeDiscountId;

            if (deletedId) {
                console.log(" [SHOPIFY SUCCESS] Discount Deleted Successfully.");
            } else {
                console.log(" [SHOPIFY DELETE FAIL]", JSON.stringify(deleteData.data?.discountCodeDelete?.userErrors, null, 2));
            }
          } 
          else {
              console.log(" [SHOPIFY] No matching active discount found to delete.");
          }
        } catch (e) { 
          console.error(" [SHOPIFY ERROR]", e.message); 
        }
      }
    } catch (error) { console.error(" Error:", error); }
  }

// CASE: ORDER CANCELLED (REVERT LOGIC)
else if (topic === "ORDERS_CANCELLED" || topic === "orders/cancelled") {
    console.log(" [ORDER CANCELLED] Processing Revert...");
    try {
     const orderIdToFind = payload.admin_graphql_api_id || `gid://shopify/Order/${payload.id}`;
        const pastOrder = await db.orderHistory.findFirst({
            where: { orderId: orderIdToFind }
        });
        if (!pastOrder) return new Response();
        const userReward = await db.rewardPoint.findFirst({
            where: { customerId: customerIdString, store: shop }
        });
        if (userReward) {
            let pointsToReturn = pastOrder.pointsRedeemed || 0; 
            let pointsToRevoke = pastOrder.pointsEarned || 0;  
            let revertValueForDB = pointsToReturn > 0 ? pointsToReturn : pointsToRevoke;
            await db.rewardPoint.update({
                where: { id: userReward.id },
                data: { 
                    pointValue: { increment: pointsToReturn - pointsToRevoke },
                    activePoint: { increment: pointsToReturn - pointsToRevoke }
                }
            });
            await db.orderHistory.update({
                where: { id: pastOrder.id }, 
                data: { 
                    pointsRevert: revertValueForDB,
                    status: "CANCELLED" 
                }
            });
            console.log(" [DB SUCCESS] User Balance & History Updated.");
            let identity = customerEmail ? customerEmail.trim() : String(customerIdString).trim();
            if (pointsToReturn > 0) {
                await updateCleverTapWallet(
                    identity, 
                    pointsToReturn, 
                    "CREDIT", 
                    readableOrderNumber, 
                    0, 
                    `Refund for Cancelled Order #${readableOrderNumber}`, 
                    shop, 
                    "ACTIVE"
                );
            }
            if (pointsToRevoke > 0) {
                await updateCleverTapWallet(
                    identity, 
                    pointsToRevoke, 
                    "DEBIT", 
                    readableOrderNumber, 
                    0, 
                    `Revoked points for Cancelled Order #${readableOrderNumber}`, 
                    shop, 
                    "ACTIVE"
                );
            }
            // D. Visual Event send
            await sendCleverTapEvent(identity, "Shopify Order Reverted", {
                "Order_ID": readableOrderNumber,
                "Points_Returned": pointsToReturn,
                "Points_Revoked": pointsToRevoke
            }, shop);
        }
    } catch (error) {
        console.error("❌ [REVERT ERROR]", error.message);
    }
}

// ----------------------------------------------------
  // 4. CASE: CHECKOUTS_UPDATE (Discount Removal Logic)
  // ----------------------------------------------------

  else if (topic === "CHECKOUTS_UPDATE" || topic === "checkouts/update") {
  const appliedDiscounts = payload.discount_codes || [];
  // 1. Check karein ki kya koi REWARD- code checkout se HATA diya gaya hai
  const hasRewardDiscount = appliedDiscounts.some(d => d.code.startsWith("REWARD-"));
  if (!hasRewardDiscount && customerIdString) {
    const searchTitle = `REWARD-${customerIdString}`;
    try {
      // 2. Shopify Admin me check karein ki kya wo code abhi bhi exist karta hai
      const response = await admin.graphql(
        `#graphql
        query FindDiscount($query: String!) {
          discountNodes(first: 1, query: $query) {
            edges {
              node {
                id
                discount {
                  ... on DiscountCodeBasic { title }
                }
              }
            }
          }
        }`,
        { variables: { query: `title:${searchTitle}*` } }
      );

      const data = await response.json();
      const node = data.data?.discountNodes?.edges[0]?.node;

      if (node) {
        const discountId = node.id;
        console.log(`🗑️ [REMOVING] Customer manually removed discount: ${node.discount.title}`);
        // 3. Delete Mutation
        const deleteMutation = `#graphql
          mutation deleteDiscount($id: ID!) {
            discountCodeDelete(id: $id) {
              deletedCodeDiscountId
              userErrors { field message }
            }
          }
        `;

        const delRes = await admin.graphql(deleteMutation, { variables: { id: discountId } });
        const delData = await delRes.json();

        if (delData.data?.discountCodeDelete?.deletedCodeDiscountId) {
          console.log("✅ [CLEANUP] Abandoned discount deleted from Admin.");
        } else {
          console.log("⚠️ [USER ERRORS]", delData.data.discountCodeDelete.userErrors);
        }
      }
    } catch (err) {
      console.error("❌ [WEBHOOK ERROR]", err.message);
    }
  }
}
  return new Response();
};